### ISSUE TITLE
For 0.2 release, the lag function does not work

### ISSUE THREAD

**Issue by java8964** [hbutani/SQLWindowing#15]
Hi, I tested with the 0.2 release. Most part of the rank works as expected, but the lag function does not work. I am still use the employees table as my test data. For the following query:

from employees
partition by department_id
order by department_id, salary desc
select r, department_id, employee_id, salary,
< lag('salary',1) - salary > as salary_gap
into path='/tmp/wout';

I expected to see for each department_id, for each employee, I will list the employee's salary, plus the gap of its salary to the highest salary in each department. There is no error from the console about processing this query, but there is no data generated.

hadoop fs -ls /tmp/wout
12/04/18 22:32:24 INFO security.UserGroupInformation: JAAS Configuration already set up for Hadoop, not re-installing.
ls: Cannot access /tmp/wout: No such file or directory.

hive> from employees
    > partition by department_id
    > order by department_id, salary desc
    > select r, department_id, employee_id, salary,
    > < lag('salary',1) - salary > as salary_gap
    > into path='/tmp/wout';
Starting Job = job_201204182053_0010, Tracking URL = http://localhost:50030/jobdetails.jsp?jobid=job_201204182053_0010
Kill Command = /home/yzhang/hadoop/bin/hadoop job  -Dmapred.job.tracker=localhost:8021 -kill job_201204182053_0010
Hadoop job information for : number of mappers: 2; number of reducers: 1
2012-04-18 22:33:03,238  map = 0%,  reduce = 0%
2012-04-18 22:33:07,249  map = 100%,  reduce = 0%
2012-04-18 22:33:14,296  map = 100%,  reduce = 33%
2012-04-18 22:33:19,324  map = 100%,  reduce = 0%
2012-04-18 22:33:26,372  map = 100%,  reduce = 33%
2012-04-18 22:33:31,405  map = 100%,  reduce = 0%
2012-04-18 22:33:39,445  map = 100%,  reduce = 33%
2012-04-18 22:33:44,470  map = 100%,  reduce = 0%
2012-04-18 22:33:51,521  map = 100%,  reduce = 33%
2012-04-18 22:33:56,545  map = 100%,  reduce = 0%
2012-04-18 22:33:57,549  map = 100%,  reduce = 100%
Map: 2  Reduce: 1   HDFS Read: 15850 HDFS Write: 0 SUCCESS
Ended Job = job_201204182053_0010

$ hadoop fs -ls /tmp/wout
12/04/18 22:34:21 INFO security.UserGroupInformation: JAAS Configuration already set up for Hadoop, not re-installing.
Found 1 items
drwxr-xr-x   - yzhang supergroup          0 2012-04-18 22:33 /tmp/wout/_logs

As you can see, I did not see the /tmp/wout/part-00000 file, which was generated when I tested the rank function, and contained the correct data as I expected in that case. But in lag function test, there is no file being generated

**Comment by hbutani** [comment]
Ok will take look tomorrow.
Thanks for being patient and continuing to test. Glad the rank function finally works. 
Will take at the null value issue.

**Comment by hbutani** [comment]
There were 2 issues with the query:
- you had 'r' in the select
- you have to explicitly specify the datatype of the expression, if you don't it assumes it is a double.

The query needed to be:
from emp
partition by department_id
order by department_id, salary desc
select department_id, employee_id, salary,
< lag('salary',1) - salary > as salary_gap[int]
into path='/tmp/wout';

But:
- should have given you an error message about the job failing; in fact in this case should have caught the issue in the parser. I am looking at this issue.
- should automatically cast from int to double; will look into this issue also

**Comment by hbutani** [comment]
I have fixed couple of the issues:
- check for unknown columns in select list
- expose errors in MR job on console; you should see a FAIL status and message about the failure.

Have not fixed the issue about specifying the datatype explicitly. I want  to first add code to analyze Groovy expressions to infer the datatype of an expression. Just adding datatype conversion to the engine to convert to the datatype of the output column may add a lot of overhead. Let me think about this.

**Comment by java8964** [comment]
OK. So I have to specify the type, in fact, the salary column is a double type column.

Any way, the following query works as I expected:

from employees
partition by department_id
order by department_id, salary desc
select department_id, employee_id, salary,
< lag('salary',1) > as salary_pre[double]
into path='/tmp/wout'

But I am not sure why the first_value function is not working. When I run the following query, no error, but still, not final file is generated in /tmp/wout:

from employees
partition by department_id
order by department_id, salary desc
select department_id, employee_id, salary,
< first_value('salary') > as high_salary[double]
into path='/tmp/wout'

Both queries are almost the same, except using different functions

**Comment by hbutani** [comment]
first_value needs to be used in a windowing clause; so your query should be written as

from employees
partition by department_id
order by department_id, salary desc
with
  first_value('salary') as high_salary
select department_id, employee_id, salary, high_salary

Lead and Lag are usable in both windowing clauses and in select statements.  In select statements you can use them to do delta computations, ratios etc. These are calculations that happen on the output after the windowing clauses are computed.
- yes since salary is double a lag expression shouldn't have to specify the type. I'm working on this.
- I haven't uploaded a new jar with the changes that print out the FAIL status. Let me do this. You will have to replace your jar with this new one.

**Comment by java8964** [comment]
Thanks. The first_value works fine. I will close this issue.
