### ISSUE TITLE
Service not found

### ISSUE THREAD

**Issue by rohitchattar** [hbutani/SQLWindowing#16]
Hi,

I cannot write to $HIVE_HOME/lib and $HIVE_HOME/bin/ext directory as our environment does not allow custom jars. 

I have set up hive --auxpath to point to groovy and windowing jar. Also copied cli.sh to my local hive user directory and renamed to wcli.sh and made the recommended changes.

i get following error:
hive --service wcli 
WARN: HADOOP_TOOLS_HOME env not set. Using  /home/y/bin/../
Service wcli not found
Available Services: cli help jar lineage rcfilecat 

Is there an environment variable to be set so that i can using windowing from non-standard location?

Rohit

**Comment by hbutani** [comment]
Hmmm. There are couple of things here:
1. SQLWIndowing is exposed as a new hive service. The hive shell script looks for a script with the name as the service arg in the bin/ext dir.
2. Not being able to copy the jars to $HIVE_HOME/lib. 

There maybe a soln to this by copying the bin directory and making changes to the shell scripts; and to use the add jar mechanism of hive. But I wonder if this is worth it.  The scripts infer HIVE_HOME based on where they are, so you will have to change this behavior...

If you are looking to test this functionality, can you install hive locally and test.

**Comment by rohitchattar** [comment]
I copied the hive home to my user dir and made the changes. Also, download datanucleas JDO jar and copied into lib dir.

I get following error now
FAILED: Error in metadata: javax.jdo.JDOFatalInternalException: Unexpected exception caught.
NestedThrowables:
java.lang.reflect.InvocationTargetException

**Comment by hbutani** [comment]
You may have to change some config settings. Can you send me the full stacktrace
