### ISSUE TITLE
job was killed,but process running..

### ISSUE THREAD

**Issue by shinjiikeda** [hbutani/SQLWindowing#18]
Hi,

I tried kill, running job In the middle.

such,
hadoop job -kill <jobid>

but, sqlwindowing query was running, 
The log such as follows was output.

2012-06-21 16:13:52,553 Stage-1 map = 41%,  reduce = 0%
2012-06-21 16:14:09,029 Stage-1 map = 42%,  reduce = 0%
Ended Job = job_201206201422_29401 with errors
Error during job, obtaining debugging information...
Examining task ID: task_201206201422_29401_m_010818 (and more) from job job_201206201422_29401
Examining task ID: task_201206201422_29401_m_000119 (and more) from job job_201206201422_29401
Examining task ID: task_201206201422_29401_m_000024 (and more) from job job_201206201422_29401
Examining task ID: task_201206201422_29401_m_000028 (and more) from job job_201206201422_29401

**Comment by hbutani** [comment]
Hi,

Can you provide some more details on the error.
Which query were you running?
Did the query hang?

regards,
Harish.
