### ISSUE TITLE
query parsing error not detected till the end

### ISSUE THREAD

**Issue by achaubal** [hbutani/SQLWindowing#4]
Hi,

While running a query, I found that even after completing the CTAS step, the windowing process plods along without any complaint, only to fumble at the end in the reduce stage if a column name is misspelt or does not exist. Shouldn't the parsing in detect that the final select, after the "with" clause has columns that are erroneous? Cause the user has no way of knowing that something errored out unless he looks at the logs. There is  a mysterious spew on the screen something like this:
attempt_201201151510_0169_r_000001_0: Query:
attempt_201201151510_0169_r_000001_0:   tableInput=(hiveTable=WindowingTempTable_1328129373936)
attempt_201201151510_0169_r_000001_0:   partitionColumns=bc_prod_acct_no
attempt_201201151510_0169_r_000001_0:   orderColumns=bc_prod_acct_no ASC, bc_date ASC
attempt_201201151510_0169_r_000001_0:   funcSpecs=[rank(alias=r, param=[], type=null, window=null),
attempt_201201151510_0169_r_000001_0:           avg(alias=ma4_ratio, param=[expr=cv_tot_bal/cv_rtl_bal_am], type=null, window=window(start=range(3 PRECEDING), end=currentRow)),
attempt_201201151510_0169_r_000001_0:           last_value(alias=prev_ratio, param=[expr=cv_tot_bal/cv_rtl_bal_am], type=null, window=window(start=range(1 PRECEDING), end=currentRow)),
attempt_201201151510_0169_r_000001_0:           ntile(alias=percentile_5, param=[intValue=5], type=null, window=null)]
attempt_201201151510_0169_r_000001_0:   select=bc_prod_acct_no, bc_date, cv_ratio, r, ma4_ratio, prev_ratio, percentile_5
attempt_201201151510_0169_r_000001_0:   whereExpr=null
attempt_201201151510_0169_r_000001_0:   tableOutput=(output(path=ma_6_2011_08, serde=org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, serDeProps={field.delim=,, columns=bc_prod_acct_no,bc_date,cv_ratio,r,ma4_ratio,prev_ratio,percentile_5, columns.types=bigint,string,double,int,double,double,int}, format=org.apache.hadoop.mapred.TextOutputFormat)

thanks

ameet

**Comment by hbutani** [comment]
Yes, this is a limitation. Currently the groovy expressions are not validated.
But if all you are doing is referring a column then for e.g.
sum(<col>) will not catch the issue but
sum(col) will catch the issue.

does this make sense. Or send me your query, let me take a look.

**Comment by achaubal** [comment]
the error was not in the "with" clause but rather the "select" that comes after the with. I was typing a wrong column name in there and it didn't detect the error till the final reduce.

Also, it doesn't catch division by zero and reports a ratio as Infinity in the final output; not sure if that's a problem or feature, but just wanted to mention.

**Comment by hbutani** [comment]
can you post your query.

**Comment by achaubal** [comment]
from         <select  acct_no,to_date(my_dt) my_date,
                      tot_bal,denom_bal
                from  mon_2011_08_all_attrib>
partition    by acct_no
    order    by acct_no,my_date asc
     with    rank() as r,
             avg (<tot_bal/denom_bal>)            over rows between 3 preceding and current row as ma4_ratio, 
             last_value(<tot_bal/denom_bal>) over rows between 1 preceding and current row as prev_ratio, 
             ntile(5) as percentile_5
   select    acct_no,my_date,**my_ratio**,r,ma4_ratio,prev_ratio,percentile_5
    into     path='ma_6_2011_08';

**my_ratio** is the column that was not available in the query, I cause made the ratio up in the **"with"** clause

**Comment by hbutani** [comment]
The error indication should happen w/o delay. This was related to issue 5.
But let me check about catching the incorrect column name in the select list
