### ISSUE TITLE
consecutive windowing queries not working

### ISSUE THREAD

**Issue by achaubal** [hbutani/SQLWindowing#5]
Hi,

After completion of one windowing query, the second windowing query gets silence from the cli. Only when I type wmode hive and quit and log back in can I execute the query.
Does it make sense? or am I missing something?

ameet

**Comment by hbutani** [comment]
this is a bug.
let me try to reproduce.
as a work around try this sequence:
wmode windowing;
issue a SQLWindowing query
wmode hive
wmode windowing
issue next SQLWindowing query

**Comment by hbutani** [comment]
Uploaded a fix for this. Downloaded the latest jars. You should now see and indication of the execution of the embedded hive query and also get details of the Job run for SQLWindowing. Here is a sample session:

> from <select origin_city_name, year, month, day_of_month, dep_time 
>              from flightsdata 
>              where dest_city_name = 'New York' and dep_time != '' and day_of_week = 1>
>            partition by origin_city_name, year, month, day_of_month
>            order by dep_time
>            with count(<year>) as c
>            select origin_city_name, year, month, day_of_month, dep_time, <lag('dep_time', 1)> as lastdep[string]
>            where <((dep_time[0..1] as int) - (lag('dep_time', 1)[0..1] as int)) \* 60 + 
>                                 ((dep_time[2..3] as int) - (lag('dep_time',1)[2..3] as int)) > 60>
>            into path='/tmp/wout' 
>            serde 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
>            with serdeproperties('field.delim'=',')
>            format 'org.apache.hadoop.mapred.TextOutputFormat'    >     >     >     >     >     >     >     >     >     >     >     > ;
> Executing Embedded Hive Query...
> Total MapReduce jobs = 2
> Launching Job 1 out of 2
> Number of reduce tasks is set to 0 since there's no reduce operator
> Starting Job = job_201202020643_0056, Tracking URL = http://localhost:50030/jobdetails.jsp?jobid=job_201202020643_0056
> Kill Command = /media/MyPassport/hadoop/hadoop-0.20.2-cdh3u1/bin/hadoop job  -Dmapred.job.tracker=localhost:8021 -kill job_201202020643_0056
> Hadoop job information for Stage-1: number of mappers: 12; number of reducers: 0
> 2012-02-02 08:58:03,189 Stage-1 map = 0%,  reduce = 0%
> 2012-02-02 08:58:06,201 Stage-1 map = 17%,  reduce = 0%
> 2012-02-02 08:58:09,219 Stage-1 map = 33%,  reduce = 0%
> 2012-02-02 08:58:12,233 Stage-1 map = 50%,  reduce = 0%
> 2012-02-02 08:58:16,247 Stage-1 map = 67%,  reduce = 0%
> 2012-02-02 08:58:21,265 Stage-1 map = 75%,  reduce = 0%
> 2012-02-02 08:58:22,271 Stage-1 map = 83%,  reduce = 0%
> 2012-02-02 08:58:25,283 Stage-1 map = 92%,  reduce = 0%
> 2012-02-02 08:58:27,289 Stage-1 map = 100%,  reduce = 0%
> 2012-02-02 08:58:30,298 Stage-1 map = 100%,  reduce = 100%
> Ended Job = job_201202020643_0056
> Ended Job = -1978976137, job is filtered out (removed at runtime).
> Launching Job 2 out of 2
> Number of reduce tasks is set to 0 since there's no reduce operator
> Starting Job = job_201202020643_0057, Tracking URL = http://localhost:50030/jobdetails.jsp?jobid=job_201202020643_0057
> Kill Command = /media/MyPassport/hadoop/hadoop-0.20.2-cdh3u1/bin/hadoop job  -Dmapred.job.tracker=localhost:8021 -kill job_201202020643_0057
> Hadoop job information for Stage-2: number of mappers: 1; number of reducers: 0
> 2012-02-02 08:58:32,651 Stage-2 map = 0%,  reduce = 0%
> 2012-02-02 08:58:33,658 Stage-2 map = 100%,  reduce = 0%
> 2012-02-02 08:58:34,664 Stage-2 map = 100%,  reduce = 100%
> Ended Job = job_201202020643_0057
> Moving data to: hdfs://localhost/user/hive/warehouse/windowingtemptable_1328201880509
> 9929 Rows loaded to hdfs://localhost/tmp/hive-harish/hive_2012-02-02_08-58-00_510_1354123372946644407/-ext-10000
> MapReduce Jobs Launched: 
> Job 0: Map: 12   HDFS Read: 655750195 HDFS Write: 256475 SUCESS
> Job 1: Map: 1   HDFS Read: 257836 HDFS Write: 256475 SUCESS
> Total MapReduce CPU Time Spent: 0 msec
> OK
> Time taken: 34.382 seconds
> done executing Embedded Hive Query.
> 12/02/02 08:58:34 INFO hive.metastore: Trying to connect to metastore with URI thrift://localhost:9083
> 12/02/02 08:58:34 INFO hive.metastore: Connected to metastore.
> 12/02/02 08:58:34 INFO hive.log: DDL: struct windowingtemptable_1328201880509 { string origin_city_name, i32 year, i32 month, i32 day_of_month, string dep_time}
> 12/02/02 08:58:35 INFO hive.metastore: Trying to connect to metastore with URI thrift://localhost:9083
> 12/02/02 08:58:35 INFO hive.metastore: Connected to metastore.
> 12/02/02 08:58:35 INFO mapred.FileInputFormat: Total input paths to process : 1
> 12/02/02 08:58:35 WARN mapred.JobClient: Use GenericOptionsParser for parsing the arguments. Applications should implement Tool for the same.
> 12/02/02 08:58:35 INFO mapred.FileInputFormat: Total input paths to process : 1
> 12/02/02 08:58:35 INFO mapred.JobClient: Running job: job_201202020643_0058
> 12/02/02 08:58:36 INFO mapred.JobClient:  map 0% reduce 0%
> 12/02/02 08:58:41 INFO mapred.JobClient:  map 100% reduce 0%
> 12/02/02 08:58:48 INFO mapred.JobClient:  map 100% reduce 33%
> 12/02/02 08:58:51 INFO mapred.JobClient:  map 100% reduce 77%
> 12/02/02 08:58:53 INFO mapred.JobClient:  map 100% reduce 100%
> 12/02/02 08:58:53 INFO mapred.JobClient: Job complete: job_201202020643_0058
> 12/02/02 08:58:53 INFO mapred.JobClient: Counters: 23
> 12/02/02 08:58:53 INFO mapred.JobClient:   Job Counters 
> 12/02/02 08:58:53 INFO mapred.JobClient:     Launched reduce tasks=1
> 12/02/02 08:58:53 INFO mapred.JobClient:     SLOTS_MILLIS_MAPS=7887
> 12/02/02 08:58:53 INFO mapred.JobClient:     Total time spent by all reduces waiting after reserving slots (ms)=0
> 12/02/02 08:58:53 INFO mapred.JobClient:     Total time spent by all maps waiting after reserving slots (ms)=0
> 12/02/02 08:58:53 INFO mapred.JobClient:     Launched map tasks=2
> 12/02/02 08:58:53 INFO mapred.JobClient:     Data-local map tasks=2
> 12/02/02 08:58:53 INFO mapred.JobClient:     SLOTS_MILLIS_REDUCES=11945
> 12/02/02 08:58:53 INFO mapred.JobClient:   FileSystemCounters
> 12/02/02 08:58:53 INFO mapred.JobClient:     FILE_BYTES_READ=548291
> 12/02/02 08:58:53 INFO mapred.JobClient:     HDFS_BYTES_READ=259573
> 12/02/02 08:58:53 INFO mapred.JobClient:     FILE_BYTES_WRITTEN=1389444
> 12/02/02 08:58:53 INFO mapred.JobClient:     HDFS_BYTES_WRITTEN=104320
> 12/02/02 08:58:53 INFO mapred.JobClient:   Map-Reduce Framework
> 12/02/02 08:58:53 INFO mapred.JobClient:     Reduce input groups=1155
> 12/02/02 08:58:53 INFO mapred.JobClient:     Combine output records=0
> 12/02/02 08:58:53 INFO mapred.JobClient:     Map input records=9929
> 12/02/02 08:58:53 INFO mapred.JobClient:     Reduce shuffle bytes=548297
> 12/02/02 08:58:53 INFO mapred.JobClient:     Reduce output records=3328
> 12/02/02 08:58:53 INFO mapred.JobClient:     Spilled Records=19858
> 12/02/02 08:58:53 INFO mapred.JobClient:     Map output bytes=528427
> 12/02/02 08:58:53 INFO mapred.JobClient:     Map input bytes=256475
> 12/02/02 08:58:53 INFO mapred.JobClient:     Combine input records=0
> 12/02/02 08:58:53 INFO mapred.JobClient:     Map output records=9929
> 12/02/02 08:58:53 INFO mapred.JobClient:     SPLIT_RAW_BYTES=262
> 12/02/02 08:58:53 INFO mapred.JobClient:     Reduce input records=9929

**Comment by achaubal** [comment]
ok this is fixed. I can run consecutive windowing queries now, thanks ameet
