### ISSUE TITLE
list of functions available

### ISSUE THREAD

**Issue by achaubal** [hbutani/SQLWindowing#6]
Hi Harish,

the doc mentions that there are 16 functions implemented in the jar. Could you please list them with a brief description?
Was wondering whether the statistical functions from the reference ORacle doc are implemented. for e.g. median, mode etc.

thx

ameet

**Comment by hbutani** [comment]
```
    registerClass(RowNumber.class);
    registerClass(Rank.class);
    registerClass(DenseRank.class);
    registerClass(CumeDist.class);
    registerClass(PercentRank.class);
    registerClass(NTile.class);

    registerClass(Sum.class);
    registerClass(Min.class);
    registerClass(Max.class);
    registerClass(Avg.class);
    registerClass(StdDev.class);
    registerClass(Count.class);

    registerClass(FirstValue.class);
    registerClass(LastValue.class);
```

plus lead & lag. 
The best way right now to get information about them is to look at the unit tests. Even if you don't program in java it is easy to extract the sample queries from the test cases. 
And if you are up to it, look at the annotations of each function in the com.sap.hadoop.windowing.functions package.

**Comment by achaubal** [comment]
thx
