### ISSUE TITLE
hive-log4j not found

### ISSUE THREAD

**Issue by achaubal** [hbutani/SQLWindowing#8]
hi harish,

the newer jars have started emitting this error on startup, 
           hive --service windowingCli -w /tmp/windowing/com.sap.hadoop.windowing-0.0.1-SNAPSHOT-jar-with-dependencies.jar
Hive history file=/tmp/ameet/hive_job_log_ameet_201202030904_2090640366.txt
**hive-log4j.properties not found**

I do have the hive-log4j.properties in /usr/lib/hive/conf/ dir and tried setting HIVE_HOME as well, but to no effect.

any thoughts?

ameet

**Comment by hbutani** [comment]
Yes this has been there in earlier versions also. Briefly looked at windowingCli.sh, don't see any difference from the other services. So don't have an explanation for this. Is this blocking you?

**Comment by achaubal** [comment]
nope

**Comment by hbutani** [comment]
Not an issue with 0.2; there are no processes spawned.
Logging based on Hive Configuration.
